ALTER TYPE "AutomationTrigger" ADD VALUE IF NOT EXISTS 'APPOINTMENT_OVERDUE';
ALTER TYPE "AutomationTrigger" ADD VALUE IF NOT EXISTS 'REFERRAL_STALE';
ALTER TYPE "AutomationTrigger" ADD VALUE IF NOT EXISTS 'TAG_ADDED';
ALTER TYPE "AutomationTrigger" ADD VALUE IF NOT EXISTS 'DOCUMENT_UPLOADED';
ALTER TYPE "AutomationTrigger" ADD VALUE IF NOT EXISTS 'AUTH_STATUS_CHANGED';
ALTER TYPE "AutomationTrigger" ADD VALUE IF NOT EXISTS 'LOCATION_REFERRAL_COUNT';
