ALTER TABLE "CardLayout" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'PROPERTIES';
ALTER TABLE "CardLayout" ADD COLUMN IF NOT EXISTS "config" JSONB;
ALTER TABLE "RecordCard" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'PROPERTIES';
ALTER TABLE "RecordCard" ADD COLUMN IF NOT EXISTS "config" JSONB;
